Create crud requirement_type
MateoCaicedoW/mjm pull request #13
Opened 2022-08-02 22:30 UTC by jolivo07

2022-08-03 18:19 UTC, rdiazrovira commented on app/routes.go
> +	root.GET("/Show/{requirement_type_id}", requirement_type.Show)
Please make this route fully lowercase.

2022-08-03 18:19 UTC, rdiazrovira commented on app/models/requirement_type.go
> +	Name         string    `form:"name" db:"name" fako:"domain_name"`
What is "domain_name"?

2022-08-03 18:23 UTC, rdiazrovira commented on app/actions/requeriment_type/requirement_type_test.go
> +	res := as.HTML("/requirement-type/").Get()
This route should be named "/requirement-types/". Plural :)

2022-08-03 18:25 UTC, rdiazrovira commented on app/actions/requeriment_type/requirement_type_test.go
> +	RequirementTypes := models.RequirementTypes{}
Please fix the name, the first character should be in lowercase.

2022-08-03 18:26 UTC, rdiazrovira commented on app/actions/requeriment_type/requirement_type_test.go
> +}
Can you validate that the requirement type has been actually updated?

2022-08-03 18:27 UTC, rdiazrovira commented on app/actions/requeriment_type/requirement_type_test.go
> +}
Please validate that the requirement type has been actually deleted.

2022-08-03 18:28 UTC, rdiazrovira requested changes
Take a look at those comments I left here.

2022-08-04 14:42 UTC, rdiazrovira approved these changes

2022-08-05 16:39 UTC, mperezlamadrid approved these changes

2022-08-05 16:39 UTC, merged