UI requirement edit
MateoCaicedoW/mjm pull request #19
Opened 2022-08-09 14:08 UTC by jolivo07

2022-08-09 20:20 UTC, mperezlamadrid approved these changes

2022-08-10 18:55 UTC, rdiazrovira commented on app/templates/requirement/form.plush.html
> +        </div>
You can use "grid" to get the correct distribution for those controls. Check the Bootstrap documentation (Grid system).

2022-08-10 18:56 UTC, rdiazrovira commented on app/assets/css/requirement.scss
> +}
Can you extract that color and move it to a css constant ?

2022-08-10 18:57 UTC, rdiazrovira commented on app/assets/css/requirement.scss
> +}
Bootstrap have already a class for it.

2022-08-10 18:59 UTC, rdiazrovira requested changes
Please take a look at the comments.

2022-08-10 22:34 UTC, rdiazrovira approved these changes

2022-08-10 22:34 UTC, merged