Table requeriment sub
MateoCaicedoW/mjm pull request #7
Opened 2022-07-27 20:08 UTC by melvinjim

2022-07-27 22:34 UTC, BryanMoslo commented on app/models/requeriment_sub.go
> +type Requirements_sub_types struct {
@mperezlamadrid Que ni Rob Pike ni Mark Bates vean esto.

2022-07-27 22:34 UTC, BryanMoslo commented on app/models/requeriment_sub.go
> +type Requirements_sub_types struct {
This should be named `RequirementsSubTypes`. In Go, structs are named in PascalCase

2022-07-27 22:34 UTC, BryanMoslo commented on migrations/20220727152706_create_table_requirement_types.up.fizz
>      t.Column("name", "string", {})
Can you please add CreatedAt and UpdatedAt, you can use `t.Timestamps()`

2022-07-27 22:34 UTC, BryanMoslo commented on migrations/20220727195202_create_table_requeriment_subs.up.fizz
> +    t.ForeignKey("requirement_type_id", {"requirement_types": ["id"]}, {"on_delete": "cascade"})
Can you please add CreatedAt and UpdatedAt, you can use `t.Timestamps()`

2022-07-28 15:46 UTC, rdiazrovira commented on app/models/requeriment_sub.go
> +type RequerimentsSubTypes struct {
A typo here. The name should be "RequirementSubType". Also of the typo, this should be named in singular. @melvinjim

2022-07-28 15:47 UTC, rdiazrovira commented on migrations/20220727195202_create_table_requeriment_subs.down.fizz
> +drop_table("requeriment_sub_types")
Same here. Please fix the typo.

2022-07-28 15:48 UTC, rdiazrovira requested changes
We have a couple of migrations files that are empty here. Please remove them If we are not going to use them.

2022-07-28 16:10 UTC, rdiazrovira commented on app/models/requeriment_sub.go
> +type RequirementSubTypes struct {
This represents an only sub type, so the name should be in singular. @melvinjim

2022-07-28 16:11 UTC, rdiazrovira commented on app/models/requeriment_sub.go
> +type RequirementSubTypes struct {
Also, fix the file names where you see the same typos.

2022-07-28 16:53 UTC, rdiazrovira approved these changes

2022-07-29 15:20 UTC, merged