Requirements
MateoCaicedoW/mjm pull request #9
Opened 2022-07-29 16:48 UTC by MateoCaicedoW

in this branch the requirements table was created and was added the departmentsID in the user model

2022-07-29 21:40 UTC, BryanMoslo reviewed
Please take a look at my suggestions @MateoCaicedoW

2022-07-29 21:40 UTC, BryanMoslo commented on app/models/departments.go
> +type Departments struct {
Please name this model in Singular.

2022-07-29 21:40 UTC, BryanMoslo commented on app/models/requirement.go
> +	RequestingDepartmentId uuid.UUID `db:"requesting_department_id"`
Acronyms is Go should be in uppercase, it should be RequestingDepartmentID

2022-07-29 21:40 UTC, BryanMoslo commented on app/models/requirement.go
> +	ServiceDepartmentId    uuid.UUID `db:"service_department_id"`
Acronyms is Go should be in uppercase.

2022-07-29 21:40 UTC, BryanMoslo commented on app/models/requirement.go
> +	RequirementSubTypeId   uuid.UUID `db:"requirement_sub_type_id"`
Acronyms is Go should be in uppercase.

2022-08-01 21:50 UTC, rdiazrovira requested changes
Multiple columns of the table **"requirements"** should be nullable.
The columns "modified_at", "approved_at", "accepted_at", "declined_at", "proccessed_at", "assigned_at", and "finished_at" must not be set with default values.
Also, please fix the typo "proccessed_at". That should be named "processed_at".

2022-08-02 14:51 UTC, rdiazrovira approved these changes

2022-08-04 16:10 UTC, merged